apiVersion: v1
data:
  handlingdb.user.name: {{ .Values.credentials.dbusername }}
  handlingdb.user.password: {{ .Values.credentials.dbpassword }}
  rabbitmq.user.name: {{ .Values.credentials.mqusername }}
  rabbitmq.user.password: {{ .Values.credentials.mqpassword }}   
kind: Secret
metadata:
  name: cargotracker-handling-credentials
type: Opaque